### ISSUE TITLE
Use a generator to add the default script command

### ISSUE THREAD

**Issue by Akryum** [multiplegeorges/vue-cli-plugin-s3-deploy#1]
The plugin could automatically add `"s3-deploy": "vue-cli-service s3-deploy --bucket=your-bucket-name",` to the user's `package.json` file when invoked, with a `generator.js` file ([docs](https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md#generator)).

**Comment by multiplegeorges** [comment]
Done!

**Comment by Akryum** [comment]
Awesome! :smile_cat:
