### ISSUE TITLE
Deploy path fails in 4.0.0-rc3

### ISSUE THREAD

**Issue by itsdrew** [multiplegeorges/vue-cli-plugin-s3-deploy#104]
`  pluginOptions: {
    s3Deploy: {
      ...
      deployPath: '/path',
     ...
    } }`

In V 3.0.0 if I set the deploy path to /path, files get deployed to the bucket as expected: bucket/path

In V4.0.0-rc3:
if I set the deploy path to '/path', files get deployed to the bucket as: bucket//path//path
if I set the deploy path to 'path', files get deployed to the bucket as: bucket/path/path

Edit: Just saw your comment on the most recent commit. Looks like you are aware of the duplicating issue. Should the deploy path start with a "/", or should we leave the leading "/" out?

**Comment by nicekiwi** [comment]
I'll have to test this.

**Comment by nicekiwi** [comment]
Yikes, this is annoying! Defo will fix. The leading `/` is supposed be the default and should be required when adding an extra path `/some/kinda/path`.

**Comment by bu-ra3y** [comment]
Fixing this would help me too.

**Comment by euan-forrester** [comment]
Also if you put the slash after, like `'path/'`, then your stuff gets uploaded with `'undefinedundefined'` prepended to every file

**Comment by nicekiwi** [comment]
RC4 has been released in @next which fixes this.  🌮
