### ISSUE TITLE
Can't install plug-in

### ISSUE THREAD

**Issue by cnmoise** [multiplegeorges/vue-cli-plugin-s3-deploy#111]
Hey all, first time submitting an issue so forgive me if I'm overlooking developer ethic

I tried to install the plug-in:

`yarn add vue-cli-plugin-s3-deploy@next`

The following error occurred
`error An unexpected error occurred: "https://amazon.goshawk.aws.a2z.com:443/npm/shared/aws-sdk/-/aws-sdk-2.648.0.tgz: Request failed \"401 Unauthorized\"".`

If I can give any more info that can help I'm happy to provide it

**Comment by nicekiwi** [comment]
Looks like an NPM error :/ does the issue persist?

**Comment by nicekiwi** [comment]
@cnmoise do you still get this error?

**Comment by nicekiwi** [comment]
Closing as OP has not replied. Hopefully it was a temporary NPM outage issue.
