### ISSUE TITLE
Integration with Github Actions

### ISSUE THREAD

**Issue by jackdcasey** [multiplegeorges/vue-cli-plugin-s3-deploy#115]
Hello! 

I love this project, and would love to contribute 😁

Would there be an interest in integration of this tool with Github Actions? I believe this workflow would be a prime candidate for automation! 

Please let me know if this would be a welcome change, and I'd be happy to get things setup. 

Otherwise, if anyone is already working on this please let me know, as I'd hate to duplicate efforts 😊

**Comment by jackdcasey** [comment]
Quick update on this, I've put together a working action:

[jackdcasey/vue-cli-plugin-s3-deploy-action](https://github.com/jackdcasey/vue-cli-plugin-s3-deploy-action)

I'll test through all the features, then if applicable add a reference to the action 😁

**Comment by nicekiwi** [comment]
Nice! :) I've added a reference to it in the Read Me.
