### ISSUE TITLE
feature request: Specific dist files

### ISSUE THREAD

**Issue by adrlen** [multiplegeorges/vue-cli-plugin-s3-deploy#14]
Hello,

Would it be possible to deploy specifics files from dist folder instead of all its content ?

If it seems interesting to you, I can try & make a pull request.

Thanks !

**Comment by multiplegeorges** [comment]
I'm trying to understand the use case here. Typically, the built files are all required for the app.

Can you give me some more details or background?

**Comment by adrlen** [comment]
I have a project where two different bundles are built according to environment, something like that : https://github.com/vuejs/vue-cli/issues/1446

**Comment by nicekiwi** [comment]
I suppose you could include an ENV override option to exclude certain files, seems a bit of en edge-case though 😸 or an exclusion regex would be better as an option; for whatever reason could be useful. And fairly easy to implement.
