### ISSUE TITLE
duplication in path when using VUE_APP_S3D_DEPLOY_PATH

### ISSUE THREAD

**Issue by ghost** [multiplegeorges/vue-cli-plugin-s3-deploy#143]
pluginVersion: "4.0.0-rc3"

`.env.development` has `VUE_APP_S3D_DEPLOY_PATH=dev` in it.
in S3 the `dist` folder's content is under /dev/dev

does https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/issues/100 seems to solve the issue. Which rc will it be available in?

**Comment by jacadarben** [comment]
Just to verify, same issue happens with  `deployPath: "dev"` in `vue.config.json`
Thanks!
