### ISSUE TITLE
Ability to set S3 Prefix for Keys?

### ISSUE THREAD

**Issue by zoul0813** [multiplegeorges/vue-cli-plugin-s3-deploy#15]
I can not seem to figure out how to set the S3 Prefix for the files.

I'd like to upload the files into a specific "folder" on the S3 bucket, as I have separate vue-cli apps for the front end and the backend/admin.  I'd like the admin uploaded to something like "/admin/".

Is this possible?

**Comment by adrlen** [comment]
I don't think it's possible for the moment. I had the same issue #13 but my problem was having different env in the same bucket from the same app, since you have different apps I don't see any workaround.

**Comment by zoul0813** [comment]
I actually found a way to get it working, by adjusting the `vue.config.js` and setting `baseUrl`, `outputDir`, `assetsDir`, and `assetPath` ... took a bit to get the correct configuration, but this was a bit clunky ... 

It would be nice if there was a single "deployment" level config option for where the app will be hosted, rather than assuming it will be hosted on the root.

**Comment by adrlen** [comment]
Yup, just thought about it when sending my answer 😄

I agree with you on that, it would be useful for #14 too.

**Comment by multiplegeorges** [comment]
Hey guys, thanks for the feature request. Sounds like you got a workaround, but I agree it's not ideal.

I'm a bit swamped with work these days, but will be able to get back to this plugin in a little while.

**Comment by multiplegeorges** [comment]
Hey all,

Just merged the addition of the `deployPath` which should get you what you're looking for.

I'll have a real release of the package soon.

**Comment by zoul0813** [comment]
I’ll try it out tomorrow hopefully - thanks!
