### ISSUE TITLE
Make deployed assets public?

### ISSUE THREAD

**Issue by eoinoc** [multiplegeorges/vue-cli-plugin-s3-deploy#17]
An excellent plugin, thank you.

I deployed to a public Amazon S3 bucket.

However, accessing that bucket was returning `403 Access Denied`. The fix was for me to manually mark the contents of the S3 bucket as public (in addition to the bucket's existing public policy).

Does this plugin allow setting the deployed S3 assets as public?

**Comment by bartlomieju** [comment]
I experience the same issue, after each deploy I need to manually mark all files as public via AWS console. Any solution would be highly appreciated.

**Comment by multiplegeorges** [comment]
Are you using the plugin with the the PWA option enabled?

**Comment by eoinoc** [comment]
No.

**Comment by nicekiwi** [comment]
I'll make a PR.

**Comment by nicekiwi** [comment]
Files uploaded to the bucket do not inherit the bucket's permissions, they will always be private. The ACL must be explicitly set for each file upon upload via the SDK uploadFile function.
