### ISSUE TITLE
dynamic urls

### ISSUE THREAD

**Issue by mikob** [multiplegeorges/vue-cli-plugin-s3-deploy#24]
Does this support dynamic urls in the route like: `order/:orderId/status` ? Does it support using history mode (html5 push state)?

Would appreciate the additional info!

**Comment by nicekiwi** [comment]
AFAIK those sorts of options are entirely independent of this plugin, you'd need to review the options in vue-router. 

So to answer your question, Yes it supports dynamic URLs in the sense that it has nothing to do with them. 😅

**Comment by mikob** [comment]
But S3 needs to have a file to represent a path AFAIK. vue-router of course should be configured but it has no control over the response that s3 returns for a given url. 

Wondering if this plugin maybe uses the s3 404 fallback hack to always return the index page -- or if it has some better technique up it's sleeves to make sure dynamic urls can be handled.

**Comment by nicekiwi** [comment]
Hmmm those settings are usually setup on the bucket itself via AWS Management Console. Though in theory the SDK can do it also.. and create the bucket; but it depends how far the functionality of the plugin should extend. 

S3 defaults to using index.html as the index and error.html as the error field, both of those should be set to index.html for 404's to work correctly, which you don't need to be done explicitly by this plugin.. though it could indeed be useful.

**Comment by multiplegeorges** [comment]
It does work if you set the 404 response document to index.html in the AWS console. I have an SPA working with History mode using these settings.

I think this setting is outside the scope of this plugin, but it would probably be helpful to mention this in the README.

**Comment by mikob** [comment]
@multiplegeorges @nicekiwi ok, thanks for the info! Was hoping this repo had a better solution because setting the error document to index.html has another set of problems with the improper response codes (404 vs 200). Anyway, was just checking, thanks again!

**Comment by nicekiwi** [comment]
@mikob you can handle the response codes in vue-router. For a SPA a static 404 shouldn't exist in anycase. However in the case where the error page is set as index.html and you access fakefile.html, it will return the index.html file but with a response code of 404.
