### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by nicekiwi** [multiplegeorges/vue-cli-plugin-s3-deploy#26]
I'll do it! :D

**Comment by multiplegeorges** [comment]
Sure, please do @nicekiwi !

**Comment by erickwilder** [comment]
@nicekiwi if you need, I'm willing to help here.

**Comment by multiplegeorges** [comment]
@erickwilder I have a branch with a small re-write of some sections and TESTS (!) :)

I'll be pushing it in a couple of days, I think. The plugin has grown to large to continue as-is.

**Comment by nicekiwi** [comment]
Ahhh, you're writing test too? :P ok

**Comment by multiplegeorges** [comment]
Just pushed a branch called https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/tree/refactor-plus-tests

It has some initial test coverage and I broke the plugin out into more logical classes.
I got deployment working with some basic settings, but it needs more work to cover all the possible option combinations and more comprehensive mocking of the actual uploading process.

**Comment by nicekiwi** [comment]
@multiplegeorges ah, the tests I was writing were written with the official vue-cli testing tools and JEST, the AWS libs are pretty easy to mock, the upload mocking is really easy..
