### ISSUE TITLE
Environment Specific Variables 

### ISSUE THREAD

**Issue by jmadda** [multiplegeorges/vue-cli-plugin-s3-deploy#29]
I'm having a problem with the variables defined in my .env files, specifically my .env.production.

I've defined all of the variables to deploy in my vue.config.js file, and I'm defaulting all of them to my development setting, then I'm overriding 3 values in my .env.production file, but they are not getting picked up.

vue.config.js
s3Deploy: {
      assetPath: 'dist',
      bucket: 'xxx-development',
      region: 'us-east-2',
      pwa: false,
      enableCloudfront: true,
      cloudfrontId: 'xxxx',
      cloudfrontMatchers: '/*',
      uploadConcurrency: 5
    }

.env.production
VUE_APP_S3D_BUCKET=xxx-production
VUE_APP_S3D_CLOUDFRONT_ID=xxx
VUE_APP_S3D_REGION=us-east-2

I also tried to remove bucket, cloudfontId, and region from the vue.config.js to force it to pull values from my .env files, but the deploy just fails without them definited in vue.config.js.

Do I need to pass the environment into the call to "vue-cli-service s3-deploy", if so, how?

**Comment by adrlen** [comment]
Did you try `vue-cli-service s3-deploy --mode production` ?

**Comment by jmadda** [comment]
I can't believe I didn't try that earlier, but I just tried it and it worked.  I had to create two entries in my package.json file, one for deploy to dev and one for production.

This should probably be mentioned in the documentation.

Thanks.

**Comment by capocasa** [comment]
I use vue-cli-service s3-deploy --mode $NODE_ENV (unixish only) and would suggest that be the default like it would appear to be the case with other vue tasks.
