### ISSUE TITLE
Use folder structure of the deployment folder when uploading

### ISSUE THREAD

**Issue by sp0ng3w0rthy** [multiplegeorges/vue-cli-plugin-s3-deploy#35]
Hey there,

Great plugin, would it be possible to enable upload of files *with* the original folder structure?
Currently files are created with the path as their name:

![image](https://user-images.githubusercontent.com/10582405/46210578-c3c7bf00-c339-11e8-92e6-77da40dfe2ea.png)

Instead of a js folder and inside it the app.3aa52735.js file.

**Comment by nicekiwi** [comment]
you wouldnt happen to be deploying from windows would you?

**Comment by thejmill** [comment]
Also having this issue using Windows.

**Comment by nicekiwi** [comment]
This is fixed in #37

**Comment by nicekiwi** [comment]
Though if you could share ur vue.config.js file @thejmill that could be helpful? :)

**Comment by thejmill** [comment]
@nicekiwi here you go.

`module.exports = {
  pluginOptions: {
    s3Deploy: {
      region: 'us-east-1',
      bucket: 'mpower-app-dev',
      assetPath: 'dist',
      deployPath: '/',
      pwa: false,
      enableCloudfront: false,
      uploadConcurrency: 5
    }
  }
}
`

**Comment by nicekiwi** [comment]
@thejmill seems legit. You could give my PR a test. Will require re-invoking the the plugin to setup the new config vars though.

**Comment by thejmill** [comment]
@nicekiwi  I'm receiving the following error when using commit 0c023fa38233038a956d7bfaae56b8afc87fad4f

 INFO  Options: {"region":"us-east-1","bucket":"mpower-app-dev","assetPath":"dist","deployPath":"/","pwa":false,"enableCloudfront":false,"uploadConcurrency":5}
 ERROR  Deploy completed with errors.
 ERROR  TypeError: Patterns must be a string or an array of strings
Done in 1.97s.

**Comment by thejmill** [comment]
@nicekiwi looks like we are good.  Created folders on s3!

**Comment by nicekiwi** [comment]
@thejmill did you run into an issue?

**Comment by thejmill** [comment]
@nicekiwi no issues.  I forgot to re-invoke the first time but after I ran "vue invoke s3-deploy" it worked without any issues.

**Comment by nicekiwi** [comment]
@thejmill ah, good :)

**Comment by multiplegeorges** [comment]
@thejmill 3.0.0 was just deployed and published to NPM. That should fix your issue.
