### ISSUE TITLE
When creating a S3 bucket, should check if the bucket name is legal 

### ISSUE THREAD

**Issue by krnan9525** [multiplegeorges/vue-cli-plugin-s3-deploy#43]
Seems like there are some characters are not allowed in S3. eg. '_' 
Should there be a werning when creating a new bucket as such?

**Comment by nicekiwi** [comment]
I think AWS should return an error for that?

**Comment by nicekiwi** [comment]
Though I will check the AWS requirements and add a check for this :)

**Comment by nicekiwi** [comment]
This feature has landed in devel for 4.0.0, but will be backported to 3.1.0.
