### ISSUE TITLE
What about versioning?

### ISSUE THREAD

**Issue by krnan9525** [multiplegeorges/vue-cli-plugin-s3-deploy#44]
When uploading some assets, should they be tagged as different versions and under different subfolders with a 'latest' one alway exists. They might not be so relevant as what a 'deploy' do, but maybe give users options for having history retentions? 

I might help you with some features if you wish 😄

**Comment by multiplegeorges** [comment]
@krnan9525 S3 has built-in support for versioning files. https://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html

**Comment by nicekiwi** [comment]
I suppose we could flag S3 to enable versioning when creating the bucket or enabling static hosting.

**Comment by nicekiwi** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putBucketVersioning-property

**Comment by nicekiwi** [comment]
I'm dropping modification of the bucket directly from the plugin, this is easy enough to do via the CLI or AWS Console.
