### ISSUE TITLE
Failed uploads to S3 exit with status code 0

### ISSUE THREAD

**Issue by erickwilder** [multiplegeorges/vue-cli-plugin-s3-deploy#47]
When uploading to S3 and an error with the upload happens, then the exit code of `npm run deploy` is `0`, meaning that it existed without errors.

It would be better to crash and make sure that the exit code is something different than zero `0` so an automation script can easily detect if a failure occurred in the upload.

---

The only possible way now to detect if everything went fine is to sniff into the `stdout` and check for `Deployment completed` text. This is a bit hacky and error-prone since the library _might_ update the output text at any point.

**Comment by multiplegeorges** [comment]
Yes, you're totally right.

This was how it used to act. I think there was a regression recently.
Thanks for the report.
