### ISSUE TITLE
[FR] Support brotli (and allow fallback to gzip)

### ISSUE THREAD

**Issue by alexandernst** [multiplegeorges/vue-cli-plugin-s3-deploy#53]
Brotli achieves better compression rates.

**Comment by nicekiwi** [comment]
@alexandernst im not sure brotli can be used with an uploader unless AWS explicitly support it in their configuration, is that the case?

**Comment by nicekiwi** [comment]
@alexandernst from what I can see compressing with Brotli is a supported feature in Webpack; so you should be able to configure this outside of this plugin. Fallbacks etc need to be configured in CloudFront or Cloudflare etc. I don't think this plugin should cover that.
