### ISSUE TITLE
Delete S3 bucket before deployed

### ISSUE THREAD

**Issue by dangvanthanh** [multiplegeorges/vue-cli-plugin-s3-deploy#54]
If I use `AWS CLI`, I can delete bucket in S3

```
aws s3 sync public s3://$S3_BUCKET --delete
```

The tool `vue-cli-plugin-s3-deploy` can delete S3 bucket before deployed.

**Comment by nicekiwi** [comment]
@dangvanthanh are you asking for this as a feature? What's the use case for that?

**Comment by dangvanthanh** [comment]
@nicekiwi I want delete old source in S3 before I run `vue-cli-plugin-s3-deploy`. Thank you very much.

**Comment by neokoenig** [comment]
This is a valid feature request I think - a simple example would be deploying a dist directory with chunked js/css - the old stuff will never be used again as is a unique filename, so is just a waste of space..

**Comment by pksunkara** [comment]
Wouldn't it be better to delete the old files rather than delete the whole bucket?

**Comment by dangvanthanh** [comment]
It's great @pksunkara .I think delete the old files better than delete bucket, too.

**Comment by abargstaedt** [comment]
> Wouldn't it be better to delete the old files rather than delete the whole bucket?

That would be very useful indeed!

**Comment by GazEdge** [comment]
should be super easy:

`aws s3 rm s3://{bucket} --recursive --profile {profile}`

Then just need to add an option to be added to vue.config.js

```
  pluginOptions: {
    s3Deploy: {
       ...
       cleanBucket: true // defaults to false
    }
  }
```

**Comment by nicekiwi** [comment]
Should be doable.

**Comment by cynodia** [comment]
This would be most useful - but please make sure you include the deploy-path as well, so that the entrie bucket is not purged if a deploy-path is used:
`aws s3 rm s3://{bucket}/{deploy-path} --recursive --profile {profile}`

**Comment by nicekiwi** [comment]
I've given up contributing to this plugin. The author seems to be MIA. I'm building my own plugin as a replacement that does include this feature.

**Comment by multiplegeorges** [comment]
@nicekiwi Hello there! Sorry I have been MIA. I believe you are have full push rights to the project.
Is there some more access you need to push it forward?

**Comment by tyhe12** [comment]
@multiplegeorges we probably need you to be also monitoring this project and releasing it when new feature added/bugs fixed 😢

**Comment by nicekiwi** [comment]
I've emailed @multiplegeorges about getting permission to publish NPM releases and add travis CI etc, you haven't replied. :(

**Comment by nicekiwi** [comment]
technically I could start releasing to GitHub Packages which can be installed via NPM without publishing to NPMJS.org.

**Comment by nicekiwi** [comment]
If i had access that is.. but I don't :(

**Comment by nicekiwi** [comment]
Tracking feature on #36
