### ISSUE TITLE
Drop PWA support

### ISSUE THREAD

**Issue by nicekiwi** [multiplegeorges/vue-cli-plugin-s3-deploy#69]
It's provided by an official Vue CLI plugin. No need to re-invent the square.

**Comment by multiplegeorges** [comment]
For a PWA to properly update itself, certain cache control settings need to be set in S3. That's what the PWA option does.

Can you explain how it is not needed in this plugin and how it is handled by the other one?

**Comment by nicekiwi** [comment]
You're right, I mis-understood the extend of AWS config needed.
