### ISSUE TITLE
No output when invoking

### ISSUE THREAD

**Issue by BernhardSchlegel** [multiplegeorges/vue-cli-plugin-s3-deploy#76]
Hey everybody,

when I run `vue invoke s3-deploy` nothing happens (no log output at all), neither on Windows 10 nor on my WSL-Ubuntu installation. Any ideas how to debug this?

Environment Info Windows:

```
Windows 10
node v8.11.2
```
Environment Info Ubuntu WSL:

```
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
node v8.10.0
```

![image](https://user-images.githubusercontent.com/5735721/62495124-5b593200-b7d5-11e9-9e43-6a7fac63f706.png)

Thanks in advance!

**Comment by aubreychiduku** [comment]
I'm having the same issue, any luck?

**Comment by nicekiwi** [comment]
Which version of the plugin are you using? 3.0.0?

**Comment by svaucher** [comment]
Same issue here. It occurred with version **3.0.0** available.

From the installation:
success Saved 1 new dependency.
info Direct dependencies
└─ vue-cli-plugin-s3-deploy@**3.0.0**

**Comment by KyleBrownCS** [comment]
I'm seeing the same issue with the following details.

```
macos catalina 10.15.2
node v13.6.0
vue-cli: "^2.9.6",
vue-cli-plugin-s3-deploy: "^3.0.0"
```

**Comment by nicekiwi** [comment]
Very curious. Can you share a public repo that reproduces the issue?
