### ISSUE TITLE
Permissions on bucket to deploy?

### ISSUE THREAD

**Issue by euan-forrester** [multiplegeorges/vue-cli-plugin-s3-deploy#79]
I found I had to set the permissions on my destination bucket a bit unexpectedly, and I wanted to ask if that was as intended, if I have a configuration issue, or if there's a bug in this plugin.

I only have one IAM user (the default user in my AWS config files), it has full control over S3, and it creates the bucket via terraform and also is the one I run as when using this plugin.

I found I had to set my bucket permissions like this:

```
resource "aws_s3_bucket_public_access_block" "frontend" {
    bucket = "${aws_s3_bucket.frontend.id}"

    block_public_acls         = false   # Needed to allow deployment into this bucket
    block_public_policy       = true
    ignore_public_acls        = true
    restrict_public_buckets   = true
}
```

I'd love to be able to set `block_public_acls` to `true`, but I get `AccessDenied` errors when I try to deploy to the bucket. Setting it to `false` allows the deployment as expected.

I also tried giving this user explicit permissions to the bucket and its contents in the bucket policy, but there was no difference (as expected, since it already has full control over s3 in its own policy).

My user's policy looks like:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                ...
                "s3:*",
                ...
            ],
            "Resource": "*"
        }
    ]
}
```

Otherwise, my bucket looks like this (with the `bucket-owner-full-control` ACL:

```
resource "aws_s3_bucket" "frontend" {
    bucket = "${var.application_name}-${var.environment}"
    acl    = "bucket-owner-full-control"
    force_destroy = true

    website {
        index_document = "index.html"
        error_document = "index.html"
    }

    ...
}
```

and my bucket policy looks like this (just allowing CloudFront to read from it):

```
data "aws_iam_policy_document" "allow_cloudfront_and_current_user" {
    statement {
        actions   = ["s3:GetObject"]
        resources = ["${aws_s3_bucket.frontend.arn}/*"]

        principals {
            type        = "AWS"
            identifiers = ["${aws_cloudfront_origin_access_identity.origin_access_identity.iam_arn}"]
        }
    }

    statement {
        actions   = ["s3:ListBucket"]
        resources = ["${aws_s3_bucket.frontend.arn}"]

        principals {
            type        = "AWS"
            identifiers = ["${aws_cloudfront_origin_access_identity.origin_access_identity.iam_arn}"]
        }
    }
}

resource "aws_s3_bucket_policy" "frontend_cloudfront_current_user" {
    bucket = "${aws_s3_bucket.frontend.id}"
    policy = "${data.aws_iam_policy_document.allow_cloudfront_and_current_user.json}"
}
```

**Comment by nicekiwi** [comment]
In theory setting staticHosting to false on the prompts should fix the access denied issues as that setting will try to set the ACLs on each file as by default uploaded files to a public bucket are not publicly accessible. But this might need further changes to be made to ACL configurations.

**Comment by nicekiwi** [comment]
Actually.. if I just added an option of `'none'` to the ACLs configuration and not try to set any when deploying that should fix this issue..

**Comment by euan-forrester** [comment]
Awesome, thank you for this!

**Comment by babinos87** [comment]
Had the same issue. I had staticHosting = false. The bucket didn't allow public access, but my local AWS credentials have enough access to put files into the bucket. 

I was getting Access Denied errors, then I saw this thread and tried @nicekiwi 's suggestion but didn't work. Inspired by that suggestion, I then tried:
`acl: undefined`
in my vue.config.js and that worked! :)

**Comment by nicekiwi** [comment]
Fixed in 4.0.0.

**Comment by euan-forrester** [comment]
@nicekiwi I just tried `4.0.0-rc2` and it still didn't work for me. I still had to set `block_public_acls` to false, otherwise I got this error:

```
Error: Upload error: AccessDenied: Access Denied
    at Deployer._callee2$ (/Users/euan/coding/photo-recommender/frontend/node_modules/vue-cli-plugin-s3-deploy/deployer.js:168:23)
    at tryCatch (/Users/euan/coding/photo-recommender/frontend/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/euan/coding/photo-recommender/frontend/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as throw] (/Users/euan/coding/photo-recommender/frontend/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/euan/coding/photo-recommender/frontend/node_modules/vue-cli-plugin-s3-deploy/deployer.js:24:103)
    at _throw (/Users/euan/coding/photo-recommender/frontend/node_modules/vue-cli-plugin-s3-deploy/deployer.js:26:291)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Am I doing something wrong?

**Comment by nicekiwi** [comment]
4.0.0 has not been released yet.

**Comment by Roriz** [comment]
I have the same issue and resolved with `acl: 'private'`. In my case, we want to force a user to consume all files from CloudFront.

**Comment by SebaSOFT** [comment]
> I have the same issue and resolved with `acl: 'private'`. In my case, we want to force a user to consume all files from CloudFront.

This should be in the docs, CloudFront backed distros should be set to private. Also your IAM user/role needs to have permission to `createInvalidation`
