### ISSUE TITLE
New NPM package version

### ISSUE THREAD

**Issue by mhluska** [multiplegeorges/vue-cli-plugin-s3-deploy#81]
Can we make a new NPM package version that includes the recently merged gzip and cache control changes?

**Comment by nicekiwi** [comment]
I'm not sure we can, it'd need to be 4.0 release. The latest NPM release is 3.0 which should still include the gzip and cache changes?

**Comment by tyhe12** [comment]
Can we release the new version some time this year? It's gonna be the best Xmas present

**Comment by nicekiwi** [comment]
AFAIK only @multiplegeorges can release an NPM version.

**Comment by adrlen** [comment]
Is it possible to release a 4.0.0-rc3 version ? Thanks.

**Comment by nicekiwi** [comment]
version `4.0.0-rc3` has been successfully released to NPM and github.
