### ISSUE TITLE
Support sync

### ISSUE THREAD

**Issue by mhluska** [multiplegeorges/vue-cli-plugin-s3-deploy#82]
With the AWS CLI tools you can do `aws s3 sync --delete s3://<src> s3://<dest>` which will sync one bucket with another. This is useful for "promoting" from a staging bucket to a production bucket. Can this package support `sync`?

**Comment by nicekiwi** [comment]
I'm not sure this fits in with this package's purpose when you can just ran that command on it's own. As this package is about deploying changes from disk to cloud, where-as that feature is deploying chnages form cloud to cloud.

**Comment by mhluska** [comment]
I’m not sure I follow the logic because this entire package can be replaced
with a few cli commands anyhow.

**Comment by nicekiwi** [comment]
This package deploys from local to s3, not from s3 to s3. I think this is well outside of the scope of this plugin.
