### ISSUE TITLE
Release permission.

### ISSUE THREAD

**Issue by nicekiwi** [multiplegeorges/vue-cli-plugin-s3-deploy#88]
@multiplegeorges please give me permission to release NPM and Github Package versions and add CI to the Repo.

**Comment by multiplegeorges** [comment]
Good idea!You should have that now.

You'll have to enable 2FA in NPM for publishing.

Thanks again for all your help with this package! 👍

**Comment by multiplegeorges** [comment]
@nicekiwi Let me know what other permissions you need on GH. I have you as a Collaborator, I don't see anywhere else to add permissions for package releases.

**Comment by nicekiwi** [comment]
I do have permissions. <3 :) thankx
