### ISSUE TITLE
Fonts are being re-uploaded everytime

### ISSUE THREAD

**Issue by sebolio** [multiplegeorges/vue-cli-plugin-s3-deploy#97]
Hello. I have a folder with fontawesome fonts located in `src/assets/webfonts` and every time i run `vue-cli-service s3-deploy` they get re-uploaded

How do I avoid this?

**Comment by nicekiwi** [comment]
Hi @sebolio which version of the plugin are you using?

**Comment by sebolio** [comment]
@nicekiwi latest, but it turns out that the building process of webpack completely regenerates the folder, making AWS S3 think they're all different files. I tried this with the CLI. So I guess there's nothing you guys can do about it.

**Comment by nicekiwi** [comment]
That is a tricky one. Keeping an exteral cache of the hash of the file contents to see which ones have and have no changed and only uploading the changed ones might be the only way. Though I'm not sure how important such a feature would be. Would save on a little bandwidth though.
