### ISSUE TITLE
not creating the static host on the s3 bucket

### ISSUE THREAD

**Issue by JGamboa** [multiplegeorges/vue-cli-plugin-s3-deploy#99]
even when staticHosting: true,
the bucket doenst create with the static hosting prop

**Comment by nicekiwi** [comment]
@JGamboa which version of the plugin are you trying? And does your AWS user have permissions to create a bucket?

**Comment by JGamboa** [comment]
@nicekiwi  the last versión, im using the root user :D has all permissions. 

Im very sorry, the bucket gets created, but doenst get configured the static hosting preference.

**Comment by nicekiwi** [comment]
@JGamboa ok, version 3.0.0 or 4.0.0-rc3?

**Comment by JGamboa** [comment]
4.0.0-rc3

**Comment by nicekiwi** [comment]
Ah, yeah I think this is a known bug. Its fixed on the dev branch.

**Comment by nicekiwi** [comment]
I'm dropping this functionality, its too annoying to maintain and test for all the edge-cases and easy enough to do via the cli and AWS Console.
